### PR TITLE
Remove asterisk from pytorch dependency's build number

### PR DESCRIPTION
**Pull request by weiji14**
Change runtime dependency constraint on pytorch, so that pytorch3d can only be installed with pytorch from the `conda-forge` channel and not the `pytorch` channel. I.e. avoid channel mixing.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Reverts #9, see rationale at https://github.com/conda-forge/pytorch3d-feedstock/pull/9#discussion_r1591594232

### CODE REVIEW

**Comment by weiji14** [comment]
@conda-forge-admin, please rerender

**Comment by weiji14** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
LGTM - is there anything else that needs doing?

**Comment by weiji14** [comment]
Oh no, I was just waiting for the tests to pass!

If you want, I can also tidy up the `recipe/meta.yaml` a bit more and/or add myself to the recipe maintainer list (though that can be done in a separate PR too).

**Comment by Tobias-Fischer** [comment]
Yes please, that’d be great. Feel free to do it here.

**Comment by weiji14** [comment]
@conda-forge-admin, please rerender

**Comment by weiji14** [comment]
Ok, should be ready now. I just added my name in, and tidied up the environment variable section at commit f30c4299a5fa91e5e16f94eac608d0896274e9f3.

**Comment by Tobias-Fischer** [comment]
Thanks @weiji14

**Pull request merged**
